name: Build, Test and Coverage

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  build-test-coverage:
    name: Build, Test & Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Build, Test and Generate Coverage
        run: ./gradlew clean check jacocoTestReport

      - name: Publish Coverage Report in Pull Request
        if: >
          github.event_name == 'pull_request' &&
          github.event.pull_request.head.repo.full_name == github.repository
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 70
          min-coverage-changed-files: 70

      - name: Upload HTML Coverage Report
        uses: actions/upload-artifact@v5
        with:
          name: jacoco-html-report
          path: build/reports/jacoco/test/html